import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtempSync,rmSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {setTimeout as delay} from 'node:timers/promises';

test('HTTP workflow enforces authentication, approvals, verification, and camera configuration',async()=>{
  const dir=mkdtempSync(join(tmpdir(),'overwatch-http-'));
  const port=35000+Math.floor(Math.random()*15000),base=`http://127.0.0.1:${port}`;
  const child=spawn(process.execPath,['server.mjs'],{cwd:new URL('..',import.meta.url),env:{...process.env,PORT:String(port),HOST:'127.0.0.1',ACCESS_CODE:'test-only-access-code',OPENAI_API_KEY:'',DB_PATH:join(dir,'test.sqlite')},stdio:'ignore'});
  try{
    let ready=false;for(let i=0;i<100;i++){try{const r=await fetch(base+'/health');if(r.ok){ready=true;break;}}catch{}await delay(30);}assert.ok(ready,'server started');
    assert.equal((await fetch(base+'/api/state')).status,401);
    assert.equal((await fetch(base+'/.env')).status,404);
    const login=await fetch(base+'/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:'test-only-access-code'})});
    assert.equal(login.status,200);assert.ok(login.headers.get('set-cookie').includes('HttpOnly'));
    const cookie=login.headers.get('set-cookie').split(';')[0];
    const request=async(path,b)=>{const r=await fetch(base+path,{method:b?'POST':'GET',headers:{Cookie:cookie,...(b?{'Content-Type':'application/json'}:{})},body:b?JSON.stringify(b):undefined});return {status:r.status,data:await r.json()};};
    const cross=await fetch(base+'/api/block',{method:'POST',headers:{Cookie:cookie,Origin:'https://untrusted.example','Content-Type':'application/json'},body:'{}'});assert.equal(cross.status,403);
    let s=(await request('/api/state')).data;assert.equal(s.inventory.length,0);assert.equal(s.vision.configured,false);
    const batch=(await request('/api/batches/start',{})).data;
    const draft=(await request('/api/draft',{batchId:batch.id,code:'OWP-RICE',requestId:'http-test-request',source:'camera'})).data;
    const duplicate=await request('/api/draft',{batchId:batch.id,code:'OWP-RICE',requestId:'http-other-device-request',source:'camera'});
    assert.equal(duplicate.status,409);assert.equal(duplicate.data.code,'DUPLICATE_BARCODE');
    assert.equal((await request('/api/draft',{code:'OWP-RICE',requestId:'http-no-batch'})).status,409);
    assert.equal((await request('/api/state')).data.inventory.length,0);
    await request(`/api/batches/${batch.id}/submit`,{});
    const laptopLogin=await fetch(base+'/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:'test-only-access-code'})});
    const laptopCookie=laptopLogin.headers.get('set-cookie').split(';')[0];
    const laptopState=await (await fetch(base+'/api/state',{headers:{Cookie:laptopCookie}})).json();
    assert.equal(laptopState.batches[0].state,'submitted');assert.equal(laptopState.tasks[0].id,draft.id);
    const approvedOnLaptop=await fetch(base+`/api/batches/${batch.id}/approve`,{method:'POST',headers:{Cookie:laptopCookie,'Content-Type':'application/json'},body:JSON.stringify({approved:true,items:[{id:draft.id,quantity:1}]})});
    assert.equal(approvedOnLaptop.status,200);
    assert.equal((await request('/api/state')).data.tasks[0].state,'received');
    assert.equal((await request('/api/state')).data.inventory.length,1);
    assert.equal((await request(`/api/tasks/${draft.id}/approve`,{quantity:1})).status,409);
    assert.equal((await request(`/api/batches/${batch.id}/approve`,{approved:true,items:[{id:draft.id,quantity:1}]})).status,200);
    assert.equal((await request(`/api/batches/${batch.id}/approve`,{approved:true,items:[{id:draft.id,quantity:1}]})).status,200);
    assert.equal((await request(`/api/tasks/${draft.id}/place`,{approved:true})).status,409);
    assert.equal((await request('/api/pickup',{code:'OWP-RICE',source:'camera',batchId:batch.id})).status,409);
    await request('/api/checkpoint',{code:'OWN:RECEIVING',source:'camera'});
    const pickup=await request('/api/pickup',{code:'OWP-RICE',source:'camera',batchId:batch.id});assert.equal(pickup.status,200);assert.equal(pickup.data.id,draft.id);
    assert.equal((await request('/api/pickup',{code:'OWP-TEA',source:'camera'})).status,409);
    const wrong=await request(`/api/tasks/${draft.id}/shelf`,{code:'OWL:B-R1-S1',source:'camera'});assert.equal(wrong.data.correct,false);
    await request(`/api/tasks/${draft.id}/shelf`,{code:'OWL:A-R1-S1',source:'camera'});
    await request(`/api/tasks/${draft.id}/item`,{code:'OWP-RICE',source:'camera'});
    assert.equal((await request(`/api/tasks/${draft.id}/place`,{approved:true})).status,409);
    const evidence={image:'data:image/jpeg;base64,'+readFileSync(new URL('fixtures/placement.jpg',import.meta.url)).toString('base64'),capturedAt:Date.now()};
    assert.equal((await request(`/api/tasks/${draft.id}/place`,{approved:true,evidence,confirmationSource:'voice'})).status,200);
    assert.equal((await request('/api/state')).data.evidence.length,1);
    assert.equal((await fetch(base+`/api/evidence/${draft.id}`)).status,401);
    const photo=await fetch(base+`/api/evidence/${draft.id}`,{headers:{Cookie:cookie}});assert.equal(photo.status,200);assert.equal(photo.headers.get('content-type'),'image/jpeg');
    assert.equal((await request('/api/transcribe',{})).status,503);
    s=(await request('/api/state')).data;assert.equal(s.inventory.length,1);assert.equal(s.inventory[0].location,'A-R1-S1');
    assert.equal((await request('/api/vision',{})).status,503);
    await request('/api/checkpoint',{code:'OWN:RECEIVING',source:'manual'});
    assert.equal((await request('/api/state')).data.checkpoint.node,'RECEIVING');
    await request('/api/block',{edge:'receiving-west',approved:true,reason:'Test obstruction'});
    assert.equal((await request('/api/state')).data.blocked.length,1);
    assert.equal((await request('/api/unblock',{edge:'receiving-west',approved:false})).status,400);
    await request('/api/unblock',{edge:'receiving-west',approved:true});
    assert.equal((await request('/api/state')).data.blocked.length,0);
    assert.equal((await fetch(base+'/')).status,200);
    assert.equal((await fetch(base+'/app.mjs')).headers.get('content-type'),'text/javascript');
    assert.equal((await fetch(base+'/labels.pdf')).status,200);
  }finally{child.kill('SIGTERM');await new Promise(resolve=>child.once('exit',resolve));rmSync(dir,{recursive:true,force:true});}
});
